### ISSUE TITLE
.side-nav fixed should behave like Angular-Material

### ISSUE THREAD

**Issue by IAMtheIAM** [sherweb/ng2-materialize#231]
1) See: [docs for Angular.io](https://angular.io/guide/form-validation) (they use angular material)
2) Make browser desktop width
3) Click hamburger menu to close nav, watch content shift left.
4) Click hamburger to open menu, watch content shift right
5) Resize browser narrow like mobile, then repeat. Notice side-nav is now an overlay, content does not shift.

Right now, using ng2-materialize, when setting sidenav to fixed,  it appears at desktop width and disappears at mobile width. This is good.

The problem is that when in desktop mode, user may want to collapse fixed sidenav menu and hide. But if we click the hamburger while fixed sidenav is already visible, it opens a new sidenav overlay on top of the existing fixed sidenav. Then clicking off will close them both. Now, clicking menu icon again will not return to fixed mode, it only open another modal which auto closes when clicking off.

The sidenav should behave exactly like how Angular.io has their sidenav, using angular material.

**Comment by jfcere** [comment]
PR #227 will allow more flexibility by exposing a `opened` state that will react accordingly when value changes (open or close the sidenav) but this will make the sidenav appears with an overlay like the sidenav on [demo page](https://sherweb.github.io/ng2-materialize/sidenav) as this is the behavior that Materialize implemented.

Although this could be done with css and that I really agree that would improve the sidenav, pushing/shifting the page content is not Materialize ready (available out of the box). For this reason, this is not something we are planning to add as we wrap Materialize, not customize Materialize (even if we do it a little sometimes).

You could always open a request on their repository for them to add this feature.

**Comment by IAMtheIAM** [comment]
OK, thats good. By the way, I understand pushing the page content would be out of scope of this wrapper project. But its very easy to accomplish for the user manually:

Just add this class the content container which would be shifted right:
```scss
.side-nav-fixed {
      @media #{$desktop-medium-and-up} {
      margin-left: 300px;
      }
   }
```

where `$desktop-medium-and-up` can be your own custom media query.
```scss
// scss variables
$desktop-medium-start: 1400px;
$desktop-medium-and-up: "only screen and (min-width : #{$desktop-medium-start})" !default;
```
Then for the sidenav to disappear at the right time:
```scss
@media #{$desktop-narrow-and-down} {
   .side-nav.fixed {
      transform: translateX(-105%) !important;
   }
}
```

Where `$desktop-narrow-and-down` is 1px less than `$desktop-medium-and-up`
```
$desktop-narrow-end: $desktop-medium-start - 1px;
$desktop-narrow-and-down: "only screen and (max-width : #{$desktop-narrow-end})" !default;
```

That is how I implemented it at least, it works good.

Having your proposed open state is a very good improvement. With that, the only last part is to make the "overlay" not appear if sidenav fixed is enabled. That can easily be done with

```scss
#sidenav-overlay {
display: none;
}

So all problems are now solved. Can someone review and merge your PR?
