### ISSUE TITLE
autocomplete input dropdown stack order

### ISSUE THREAD

**Issue by utk3012** [sherweb/ng2-materialize#323]
The autocomplete input (https://sherweb.github.io/ng2-materialize/input) dropdown pushes down the elements below the input instead of coming in front of the elements like a default search engine autocomplete dropdown.
Is there a work around to it?
The dropdown is dynamically added so applying CSS to it not possible.

**Comment by scote** [comment]
It seems to be a bug in Materialize version 100.2.
http://archives.materializecss.com/0.100.2/forms.html

**Comment by viniciosyals** [comment]
I solved it this way

styles.scss
```css
mz-input-container {
	.autocomplete-content {
		position: absolute;
		width: 100% !important;
	}
}
```
